apiVersion: v1
kind: Service
metadata:
  name: efficientnet-model-service
spec:
  selector:
    app: efficientnet-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
